stages:
  data_ingestion:
    cmd: python Easy_Visa/components/data_ingestion.py
    deps:
      - CSV_Data/EasyVisa.csv
      - Easy_Visa/components/data_ingestion.py
    outs:
      - artifacts/data_ingestion

  data_validation:
    cmd: python Easy_Visa/components/data_validation.py
    deps:
      - Easy_Visa/components/data_validation.py
      - config/schema.yaml 
      - artifacts/data_ingestion
    outs:
      - artifacts/data_validation

  data_transformation:
    cmd: python Easy_Visa/components/data_transformation.py
    deps:
      - Easy_Visa/components/data_transformation.py
      - artifacts/data_validation
      - config/schema.yaml 
    outs:
      - artifacts/data_transformation

  model_trainer:
    cmd: python Easy_Visa/components/model_trainer.py
    deps:
      - Easy_Visa/components/model_trainer.py
      - artifacts/data_transformation
    outs:
      - artifacts/model_trainer

  model_evaluation:
    cmd: python Easy_Visa/components/model_evaluation.py
    deps:
      - Easy_Visa/components/model_evaluation.py
      - artifacts/model_trainer
      - artifacts/data_ingestion
    outs:
      - artifacts/model_evaluation

  model_pusher:
    cmd: python Easy_Visa/components/model_pusher.py
    deps:
      - Easy_Visa/components/model_pusher.py
      - artifacts/model_evaluation
    outs:
      - artifacts/model_pusher